const ADD_ANNOUNCEMENT = 'ADD_ADDOUNCEMENT';
const REMOVE_ANNOUNCEMENT = 'REMOVE_ANNOUNCEMENT';
const ACTIVATE_ANNOUNCEMENT = 'ACTIVATE_ANNOUNCEMENT';
const DEACTIVATE_ANNOUNCEMENT = 'DEACTIVATE_ANNOUNCEMENT';